name: syoft_task
description: Syoft Task
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: 3.2.0
  connectivity_plus: 2.2.0
 
  cupertino_icons: 1.0.5
  dio: 4.0.6
  flutter_screenutil: 5.5.3+2
  flutter_svg: 0.23.0+1
  get: 4.6.0
  google_fonts: 2.2.0
  lottie: 1.2.2
  intl: 0.17.0
  shimmer: 2.0.0
  shared_preferences: 2.0.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  
